FROM ubuntu:xenial-20181113

ENV DEBIAN_FRONTEND=noninteractive

RUN set -e -x ;\
    apt-get -y update ;\
    apt-get -y upgrade ;\
    apt-get -y install \
        build-essential autoconf cmake clang bison wget flex gperf \
        libreadline-dev gawk tcl-dev libffi-dev graphviz xdot python3-dev \
        libboost-all-dev qt5-default git libftdi-dev pkg-config libeigen3-dev \
        zlib1g-dev

RUN set -e -x ;\
    mkdir -p /usr/local/src ;\
    cd /usr/local/src ;\
    git clone --recursive https://github.com/steveicarus/iverilog.git ;\
    cd iverilog ;\
    git reset --hard 172d7eb0a3665f89b91d601b5912c33acedc81e5 ;\
    sh autoconf.sh ;\
    ./configure ;\
    make -j $(nproc) ;\
    make install ;\
    rm -rf /usr/local/src/iverilog

RUN set -e -x ;\
    mkdir -p /usr/local/src ;\
    cd /usr/local/src ;\
    git clone --recursive https://github.com/YosysHQ/icestorm.git ;\
    cd icestorm ;\
    git reset --hard 4bc68c9620e6be20f8fe10d20f84681d80beac23 ;\
    make -j $(nproc) ;\
    make install

RUN set -e -x ;\
    mkdir -p /usr/local/src ;\
    cd /usr/local/src ;\
    git clone --recursive https://github.com/YosysHQ/yosys.git ;\
    cd yosys ;\
    git reset --hard cd8b2ed4e6f9447c94d801de7db7ae6ce0976d57 ;\
    make -j $(nproc) ;\
    make install ;\
    rm -rf /usr/local/src/yosys

RUN set -e -x ;\
    mkdir -p /usr/local/src ;\
    cd /usr/local/src ;\
    git clone --recursive https://github.com/YosysHQ/prjtrellis.git ;\
    cd prjtrellis ;\
    git reset --hard 7831b54f619d6695855525fca776543b7c827704 ;\
    cd libtrellis ;\
    cmake . ;\
    make -j $(nproc) ;\
    make install
