FROM ubuntu:xenial-20181113

ENV DEBIAN_FRONTEND=noninteractive

RUN set -e -x ;\
    apt-get -y update ;\
    apt-get -y upgrade ;\
    apt-get -y install \
        build-essential cmake clang python3-dev libboost-all-dev qt5-default git

RUN set -e -x ;\
    apt-get -y install \
        libftdi-dev pkg-config

RUN set -e -x ;\
    mkdir -p /usr/local/src ;\
    cd /usr/local/src ;\
    git clone --recursive https://github.com/cliffordwolf/icestorm.git ;\
    cd icestorm ;\
    git reset --hard 9671b760f84ca4006f0ef101a3e3b201df4eabb5 ;\
    make -j $(nproc) ;\
    make install

RUN set -e -x ;\
    mkdir -p /usr/local/src ;\
    cd /usr/local/src ;\
    git clone --recursive https://github.com/SymbiFlow/prjtrellis.git ;\
    cd prjtrellis ;\
    git reset --hard de035a6e5e5818804a66b9408f0ad381b10957db ;\
    cd libtrellis ;\
    cmake -DCMAKE_INSTALL_PREFIX=/usr . ;\
    make -j $(nproc) ;\
    make install
