[package]
name = "awooter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "awooter"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
libc = "0.2"
