/*
 *  nextpnr -- Next Generation Place and Route
 *
 *  Copyright (C) 2018  gatecat <gatecat@ds0.me>
 *
 *  Permission to use, copy, modify, and/or distribute this software for any
 *  purpose with or without fee is hereby granted, provided that the above
 *  copyright notice and this permission notice appear in all copies.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 *  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 *  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 *  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 *  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 *  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 *  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 *
 */

#ifndef HIMBAECHEL_EXAMPLE_GFX_H
#define HIMBAECHEL_EXAMPLE_GFX_H

#include "nextpnr.h"

NEXTPNR_NAMESPACE_BEGIN

enum GfxTileWireId
{
    TILE_WIRE_NONE,

    TILE_WIRE_L0_O,
    TILE_WIRE_L1_O,
    TILE_WIRE_L2_O,
    TILE_WIRE_L3_O,
    TILE_WIRE_L4_O,
    TILE_WIRE_L5_O,
    TILE_WIRE_L6_O,
    TILE_WIRE_L7_O,

    TILE_WIRE_L0_I0,
    TILE_WIRE_L0_I1,
    TILE_WIRE_L0_I2,
    TILE_WIRE_L0_I3,

    TILE_WIRE_L1_I0,
    TILE_WIRE_L1_I1,
    TILE_WIRE_L1_I2,
    TILE_WIRE_L1_I3,

    TILE_WIRE_L2_I0,
    TILE_WIRE_L2_I1,
    TILE_WIRE_L2_I2,
    TILE_WIRE_L2_I3,

    TILE_WIRE_L3_I0,
    TILE_WIRE_L3_I1,
    TILE_WIRE_L3_I2,
    TILE_WIRE_L3_I3,

    TILE_WIRE_L4_I0,
    TILE_WIRE_L4_I1,
    TILE_WIRE_L4_I2,
    TILE_WIRE_L4_I3,

    TILE_WIRE_L5_I0,
    TILE_WIRE_L5_I1,
    TILE_WIRE_L5_I2,
    TILE_WIRE_L5_I3,

    TILE_WIRE_L6_I0,
    TILE_WIRE_L6_I1,
    TILE_WIRE_L6_I2,
    TILE_WIRE_L6_I3,

    TILE_WIRE_L7_I0,
    TILE_WIRE_L7_I1,
    TILE_WIRE_L7_I2,
    TILE_WIRE_L7_I3,

    TILE_WIRE_L0_D,
    TILE_WIRE_L1_D,
    TILE_WIRE_L2_D,
    TILE_WIRE_L3_D,
    TILE_WIRE_L4_D,
    TILE_WIRE_L5_D,
    TILE_WIRE_L6_D,
    TILE_WIRE_L7_D,

    TILE_WIRE_L0_Q,
    TILE_WIRE_L1_Q,
    TILE_WIRE_L2_Q,
    TILE_WIRE_L3_Q,
    TILE_WIRE_L4_Q,
    TILE_WIRE_L5_Q,
    TILE_WIRE_L6_Q,
    TILE_WIRE_L7_Q,

    TILE_WIRE_RAM_WA0,
    TILE_WIRE_RAM_WA1,
    TILE_WIRE_RAM_WA2,
    TILE_WIRE_RAM_WA3,
    TILE_WIRE_RAM_WA4,
    TILE_WIRE_RAM_WA5,
    TILE_WIRE_RAM_WA6,
    TILE_WIRE_RAM_WA7,
    TILE_WIRE_RAM_WA8,

    TILE_WIRE_RAM_RA0,
    TILE_WIRE_RAM_RA1,
    TILE_WIRE_RAM_RA2,
    TILE_WIRE_RAM_RA3,
    TILE_WIRE_RAM_RA4,
    TILE_WIRE_RAM_RA5,
    TILE_WIRE_RAM_RA6,
    TILE_WIRE_RAM_RA7,
    TILE_WIRE_RAM_RA8,

    TILE_WIRE_RAM_WE0,
    TILE_WIRE_RAM_WE1,

    TILE_WIRE_RAM_DI0,
    TILE_WIRE_RAM_DI1,
    TILE_WIRE_RAM_DI2,
    TILE_WIRE_RAM_DI3,
    TILE_WIRE_RAM_DI4,
    TILE_WIRE_RAM_DI5,
    TILE_WIRE_RAM_DI6,
    TILE_WIRE_RAM_DI7,
    TILE_WIRE_RAM_DI8,
    TILE_WIRE_RAM_DI9,
    TILE_WIRE_RAM_DI10,
    TILE_WIRE_RAM_DI11,
    TILE_WIRE_RAM_DI12,
    TILE_WIRE_RAM_DI13,
    TILE_WIRE_RAM_DI14,
    TILE_WIRE_RAM_DI15,

    TILE_WIRE_RAM_DO0,
    TILE_WIRE_RAM_DO1,
    TILE_WIRE_RAM_DO2,
    TILE_WIRE_RAM_DO3,
    TILE_WIRE_RAM_DO4,
    TILE_WIRE_RAM_DO5,
    TILE_WIRE_RAM_DO6,
    TILE_WIRE_RAM_DO7,
    TILE_WIRE_RAM_DO8,
    TILE_WIRE_RAM_DO9,
    TILE_WIRE_RAM_DO10,
    TILE_WIRE_RAM_DO11,
    TILE_WIRE_RAM_DO12,
    TILE_WIRE_RAM_DO13,
    TILE_WIRE_RAM_DO14,
    TILE_WIRE_RAM_DO15,
};

NEXTPNR_NAMESPACE_END

#endif
