set_property PACKAGE_PIN L13 [get_ports clk]

set_property PACKAGE_PIN E17 [get_ports led[0]]
set_property PACKAGE_PIN F13 [get_ports led[1]]
set_property PACKAGE_PIN G13 [get_ports led[2]]
set_property PACKAGE_PIN F14 [get_ports led[3]]
set_property PACKAGE_PIN L16 [get_ports led[4]]
set_property PACKAGE_PIN L15 [get_ports led[5]]
set_property PACKAGE_PIN L20 [get_ports led[6]]
set_property PACKAGE_PIN L19 [get_ports led[7]]
set_property PACKAGE_PIN R17 [get_ports led[8]]
set_property PACKAGE_PIN R18 [get_ports led[9]]
set_property PACKAGE_PIN U20 [get_ports led[10]]
set_property PACKAGE_PIN T20 [get_ports led[11]]
set_property PACKAGE_PIN W20 [get_ports led[12]]
set_property PACKAGE_PIN V20 [get_ports led[13]]

set_property PACKAGE_PIN G14 [get_ports pb0]
set_property PACKAGE_PIN G15 [get_ports pb1]

set_property PACKAGE_PIN N14 [get_ports sw[0]]
set_property PACKAGE_PIN M14 [get_ports sw[1]]
set_property PACKAGE_PIN M16 [get_ports sw[2]]
set_property PACKAGE_PIN M15 [get_ports sw[3]]
set_property PACKAGE_PIN N15 [get_ports sw[4]]
set_property PACKAGE_PIN N16 [get_ports sw[5]]
set_property PACKAGE_PIN M17 [get_ports sw[6]]
set_property PACKAGE_PIN M18 [get_ports sw[7]]

set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports led[0]]
set_property IOSTANDARD LVCMOS33 [get_ports led[1]]
set_property IOSTANDARD LVCMOS33 [get_ports led[2]]
set_property IOSTANDARD LVCMOS33 [get_ports led[3]]
set_property IOSTANDARD LVCMOS33 [get_ports led[4]]
set_property IOSTANDARD LVCMOS33 [get_ports led[5]]
set_property IOSTANDARD LVCMOS33 [get_ports led[6]]
set_property IOSTANDARD LVCMOS33 [get_ports led[7]]
set_property IOSTANDARD LVCMOS33 [get_ports led[8]]
set_property IOSTANDARD LVCMOS33 [get_ports led[9]]
set_property IOSTANDARD LVCMOS33 [get_ports led[10]]
set_property IOSTANDARD LVCMOS33 [get_ports led[11]]
set_property IOSTANDARD LVCMOS33 [get_ports led[12]]
set_property IOSTANDARD LVCMOS33 [get_ports led[13]]

set_property IOSTANDARD LVCMOS33 [get_ports pb0]
set_property IOSTANDARD LVCMOS33 [get_ports pb1]

set_property IOSTANDARD LVCMOS33 [get_ports sw[0]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[1]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[2]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[3]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[4]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[5]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[6]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[7]]