import sys
from os import path

# TODO: Add the option to precompile kernels to SPIR-V

with open(sys.argv[-1], "w") as cc:
	programs = []
	print('/* Generated by embed_kernels.py */', file=cc)
	print('#include "nextpnr.h"', file=cc)
	print('NEXTPNR_NAMESPACE_BEGIN', file=cc)
	for program_filename in sys.argv[1:-1]:
		with open(program_filename, 'r') as kf:
			program_name = path.splitext(path.basename(program_filename))[0]
			print('static const std::string program_{} = '.format(program_name), file=cc)
			print('        R"krnl({})krnl";'.format(kf.read()), file=cc)
			print("", file=cc)
			programs.append(program_name)
	print('const std::string &get_opencl_source(const std::string &name) {', file=cc)
	for program in programs:
		print('    if (name == "{}")'.format(program), file=cc)
		print('        return program_{};'.format(program), file=cc)
	print('    NPNR_ASSERT_FALSE("OpenCL program lookup failed");', file=cc)
	print('}', file=cc)
	print("", file=cc)
	print('NEXTPNR_NAMESPACE_END', file=cc)
